### ISSUE TITLE
If the design is close enough to djangoproject.com, consult the original authors

### ISSUE THREAD

**Issue by aaugustin** [chadwhitman/chadwhitman.github.io#12]
If the "welcome page" is close enough to the style of djangoproject.com, it would be polite to check with the various designers of djangoproject.com if they're OK with it, all the more considering that 
the licensing history of djangoproject.com isn't very clear. A license was added late in the process: https://github.com/django/djangoproject.com/issues/477

The people to consult would be https://github.com/django/djangoproject.com/blob/master/djangoproject/scss/_style.scss#L2-L9. 

Of course, if we end up with something visually distinct, there's nothing to do.

Thanks @jezdez for the heads up and the references.

**Comment by FlipperPA** [comment]
I spoke with Michael Trythall from the DjangoProject.com design team, and he gave us an enthusiastic thumbs up.

via the DjangoCon US Slack:

> And as a designer, Django.. community.. member, and person who did a little bit of code I think it's fine :thumbsup: In fact I'd argue it's better that it's all in sync, honestly. Good job!

**Comment by jezdez** [comment]
@FlipperPA Hi there, I was the contact on the DSF board for the effort to ship the current Django website design with the contractor Andrew McCarthy, who finished the design and frontend code that was previously donated by Threespot (Jes Gundy) to the Django project.

Here's the list of people to ping and ask if they are okay with shipping some design elements of the website with Django releases:

- [ ] @jesgundy - Jes Gundy
- [ ] @andrevvm - Andrew McCarthy
- [x] @mtrythall - Michael Trythall

Please make sure to follow up with all of them, so we're in the clear since the original work done for the website didn't encompass distributing it as part of the Django releases.

**Comment by jesgundy** [comment]
I'm no longer with Threespot but you can reach out to their lead engineer - @tedw - with any questions you might have regarding the front-end work we completed. Hope that helps!

**Comment by tedw** [comment]
Threespot is happy to defer to the Django team on this and all future matters :)

**Comment by FlipperPA** [comment]
Ah, my apologies @jezdez. Does this mean we're approved, @tedw and @jesgundy? Thank you!

**Comment by mtrythall** [comment]
For anyone following (and because I'm curious), in the future, how should this sort of thing be handled? Is there a BDFL of Django Design (anymore)? Or is it just the DSF board as a whole?

**Comment by jezdez** [comment]
@mtrythall I don't think Idan is still in this role, and in many cases we've had trouble answering questions regarding the design (visual and otherwise) because there was little expertise on the board (e.g. hence the delay in implementation of the website design for example).

In case of questions regarding the trademark policy please see the [agreement](https://www.djangoproject.com/trademarks/) and the [FAQ](https://www.djangoproject.com/trademarks/faq/) respectively. In doubt it's best to ping the board. Even though there is a likelihood that the current directors don't know either as they weren't around for past decisions, it's a good starting point.

**Comment by FlipperPA** [comment]
I wanted to see if there was any way to get @andrevvm to chime in? @jezdez, do you happen to have contact information for him? Thank you.
